# Generated by Django 4.2.3 on 2024-08-08 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ctfTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(default='Task', max_length=30)),
                ('task_text', models.TextField()),
                ('task_description', models.TextField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('points', models.IntegerField(default=0)),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Задание CTF',
                'verbose_name_plural': 'Задания CTFs',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_task.ctftask')),
            ],
            options={
                'verbose_name': 'Ответ пользователя CTF',
                'verbose_name_plural': 'Ответы пользователей CTF',
            },
        ),
    ]
