# Generated by Django 4.2.3 on 2024-08-09 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'verbose_name': 'Ответ пользователя на задания CTF', 'verbose_name_plural': 'Ответы пользователей на задания CTF'},
        ),
    ]
