# Generated by Django 4.2.3 on 2024-08-09 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0002_alter_submission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ctftask',
            options={'verbose_name': 'Задание CTF для одиночных пользователей', 'verbose_name_plural': 'Задания CTFs для одиночных пользователей'},
        ),
    ]
