# Generated by Django 4.2.3 on 2024-08-10 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0003_alter_ctftask_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ctfTask',
            new_name='Task',
        ),
    ]
