# Generated by Django 4.2.3 on 2024-09-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0006_alter_task_title_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='difficulty',
            field=models.CharField(default='Легкое', max_length=200),
        ),
    ]
