# Generated by Django 4.2.3 on 2024-09-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0008_submission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='material_file',
            field=models.FileField(blank=True, null=True, upload_to='task_materials/'),
        ),
    ]
