# Generated by Django 4.2.3 on 2024-09-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0009_task_material_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='type_task',
            field=models.CharField(default='', max_length=255),
        ),
    ]
