# Generated by Django 4.2.3 on 2024-08-09 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0002_alter_choice_options_alter_result_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Tests',
        ),
    ]
