# Generated by Django 4.2.3 on 2024-09-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0003_rename_tasks_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='test_description',
            field=models.CharField(default='Описание теста', max_length=120),
        ),
    ]
