# Generated by Django 4.2.3 on 2024-09-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamUser',
        ),
    ]
