# Generated by Django 4.2.3 on 2024-09-21 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_singleuser_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singleuser',
            old_name='name',
            new_name='first_name',
        ),
    ]
