# Generated by Django 4.2.3 on 2024-09-21 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_rename_name_singleuser_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singleuser',
            old_name='profession',
            new_name='city',
        ),
    ]
