# Generated by Django 4.2.3 on 2024-09-22 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_profile_delete_singleuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='first_name',
        ),
    ]
