# Generated by Django 4.2.3 on 2024-09-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0007_rename_name_profile_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='event_points',
            field=models.IntegerField(default=0),
        ),
    ]
