# Generated by Django 4.2.3 on 2024-09-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gallery', '0002_alter_image_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/articles'),
        ),
    ]
